# helpers/llm_utils.py
import os
from openai import OpenAI

client = OpenAI(
    api_key = os.getenv("OPENAI_API_KEY"),
)

if not client.api_key:
    raise ValueError("API key not found. Please set the OPENAI_API_KEY environment variable.")


def generate_llm_natural_output(plain_summary):
    """
    Uses OpenAI's API to take a plain language summary of data and refine it,
    making it even more user-friendly.
    
    Args:
        plain_summary (str): The summary string generated from the DataFrame's describe().
        
    Returns:
        str: A refined natural language output generated by the LLM.
    """
    prompt = (
    "You are an expert data analyst. The following text is a summary of statistical "
    "results generated from student data. Rewrite the summary in clear, plain language "
    "that is professional and suitable for non-technical stakeholders. The final summary should "
    "describe the key findings in a concise, conversational tone and highlight what the data indicates "
    "about student performance.\n\n"
    f"{plain_summary}\n\n"
    "Refined Summary:"
    )
    
    response = client.responses.create(
    model="gpt-4o",
    input=prompt
    )
    refined_text = response.output_text
    return refined_text
